version : '3'

services:
  web-app:
    container_name: customer_react_project
    build:
      context : .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3001

    volumes:
      - '/app/node_modules'
      - '.:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true


