FROM node:13.12.0-alpine  as Builder


WORKDIR '/app'

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json .
COPY package-lock.json .
RUN npm install -silent
RUN npm install react-script@latest -g -silent

COPY . .
CMD npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx","-g","daemon off"]